PaydirektEditViewController layout
snabble/iOS-SDK pull request #101
Opened 2022-04-19 07:28 UTC by mobileapps23

- programmatic layout for PaydirektEditViewController

2022-04-20 09:02 UTC, mrgrauel requested changes

2022-04-20 09:02 UTC, mrgrauel commented on Snabble/UI/de.lproj/SnabbleLocalizable.strings
> +"Snabble.paydirekt.title" = "paydirekt";
We use phrase.com for translations. 8caa630bdb1e0966973630cba7c96aeaa5ccd0ca
If you find something like that let me know.

2022-04-21 12:23 UTC, mobileapps23 commented on Snabble/UI/PaymentMethods/PaydirektEditViewController.swift
> +    public init(_ detail: PaymentMethodDetail?, with analyticsDelegate: AnalyticsDelegate?) {
Then should be also changed init methods for `TeleCashCreditCardEditViewController`, `PayoneCreditCardEditViewController`, `SepaEditViewController`, `PayoneCreditCardEditViewController`, `DatatransAliasViewController`, etc.
And logic for creation entry points:
 at `MethodRegistry` -> 
`createEntry(method: RawPaymentMethod, _ projectId: Identifier<Project>, _ analyticsDelegate: AnalyticsDelegate?) -> UIViewController?`
at `DatatransFactory` enum, etc.
Do we need this kind of refactoring now? I can make it as separate pull request, if yes.

2022-04-21 12:23 UTC, mobileapps23 commented on Snabble/UI/PaymentMethods/PaydirektEditViewController.swift
>      private var webView: WKWebView?
Fixed

2022-04-21 12:24 UTC, mobileapps23 commented on Snabble/UI/PaymentMethods/PaydirektEditViewController.swift
> +        self.view = view
Fixed

2022-04-21 12:24 UTC, mobileapps23 commented on Snabble/UI/PaymentMethods/PaydirektEditViewController.swift
> +        }
Fixed

2022-04-21 13:16 UTC, mrgrauel commented on Snabble/UI/PaymentMethods/PaydirektEditViewController.swift
> +    public init(_ detail: PaymentMethodDetail?, with analyticsDelegate: AnalyticsDelegate?) {
No, you are correct that's out of scope.

2022-04-21 13:55 UTC, mrgrauel requested changes
[Screen Shot 2022-04-21 at 15 54 19](https://user-images.githubusercontent.com/148758/164473527-a7d807dc-8547-4c5f-ae17-f0ee9895debf.png)

I see an empty screen when I try to add Paydirekt for Tegut (Environment: Testing)

2022-04-22 14:49 UTC, mobileapps23 commented
When try to add Paydirekt for Tegut (Environment: Testing) there is an empty screen because link for paydirekt is `nil` in `Metadata`:
line 163 - `let authUrl = Snabble.metadata.links.paydirektCustomerAuthorization?.href,`
output for `links` is -
`MetadataLinks(
clientOrders: Optional(SnabbleSDK.Link(href: "/clients/{clientID}/orders")), 
appUser: SnabbleSDK.Link(href: "/apps/users/{appUserID}"), 
appUserOrders: SnabbleSDK.Link(href: "/apps/users/{appUserID}/orders"), 
consents: Optional(SnabbleSDK.Link(href: "/apps/users/{appUserID}/consents")), 
paydirektCustomerAuthorization: nil, 
createAppUser: SnabbleSDK.Link(href: "/apps/snabble-app-quae3M/users"), 
_self: SnabbleSDK.Link(href: "/metadata/app/snabble-app-quae3M/ios/2.9.1"))`

and there is no handling for this case(and also for every failure case at `func startAuthorization()`).
It's better to add an alert, and need to know title and message for it.

Another question is about line 164 - `let project = Snabble.projects.first`
Is it correct way here to define current project without its id? Because it always will give an 'Aldi', as it is the first one in the array. I guess, it should be changed to` Snabble.project(for projectId: Identifier<Project>)`, and `viewController` should be initialized with `projectId` parameter.

2022-04-25 07:18 UTC, mrgrauel commented
It's all correct 👍 

Do you want to refactor it as you mentioned? For me the network layer shouldn't need a `project` instance, but that's something we have to do in the future.

2022-04-25 09:19 UTC, merged