add shop identifier to rating event
snabble/iOS-SDK pull request #15
Opened 2021-01-18 15:04 UTC by mrgrauel

2021-01-18 15:28 UTC, gereons requested changes

2021-01-18 15:28 UTC, gereons commented on Snabble/Core/Events/AppEvents.swift
>          self.init(type: .analytics, payload: analytics, project: project)
Hier muss noch die shopId übergeben werden :)

2021-01-19 06:03 UTC, mrgrauel commented on Snabble/Core/Events/AppEvents.swift
>          self.init(type: .analytics, payload: analytics, project: project)
9548cdbacced0971601fd4aa14ace430a34aca34

2021-01-19 07:15 UTC, gereons approved these changes

2021-01-19 07:23 UTC, merged