Add QR code headline, adaptive layout
snabble/iOS-SDK pull request #22
Opened 2021-01-29 08:23 UTC by gereons

Fixes #21

2021-01-29 09:43 UTC, mrgrauel requested changes
Es funktioniert noch nicht richtig. Auf dem iPhone SE (1st Generation) wird mir nun kein Code angezeigt. Ebenso dachte ich es soll *Code 1 von 1* nicht angezeigt werden wenn es nur einen gibt.

[Simulator Screen Shot - iPhone SE (1st generation) - 2021-01-29 at 10 41 07](https://user-images.githubusercontent.com/148758/106258796-9b5c7200-621e-11eb-854f-1fbd0e391c39.png)

2021-02-01 08:24 UTC, gereons commented
Falls das untergegangen sein sollte: https://github.com/snabble/iOS-SDK/pull/22/commits/2c25eff316618d976a105506da6cb5198b62993d ist der Fix für den Bug.

2021-02-01 08:51 UTC, mrgrauel commented
Darüber bekomme ich keine Mitteilung. Gerne daraufhin einen Kommentar in Zukunft.

2021-02-01 10:10 UTC, mrgrauel requested changes
@gereons ich sehe leider weiterhin auf dem iPhoneSE die Headergrafik und den Pfeil. In den Designvorgaben https://github.com/snabble/snabble/issues/98 sollte das alte iPhoneSE kein Headergrafik haben.

![Simulator Screen Shot - iPhone SE (1st generation) - 2021-02-01 at 11 01 43](https://user-images.githubusercontent.com/148758/106443593-f095bf00-647c-11eb-8b64-bb421aa13ca6.png)

Das aktuelle iPhone SE hat den Pfeil, obwohl er nicht angezeigt werden sollte.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-02-01 at 11 06 43](https://user-images.githubusercontent.com/148758/106444136-a5c87700-647d-11eb-8179-85702061d787.png)

2021-02-01 12:10 UTC, mrgrauel commented
Sorry es geht wohl alles. Ich kann es auf den Simulatoren nicht testen, da `DeviceKit` noch nicht die Simulatoren von Apple Silicon unterstützt. Siehe https://github.com/devicekit/DeviceKit/pull/273

2021-02-01 12:10 UTC, mrgrauel approved these changes

2021-02-01 12:16 UTC, merged