Apps 764
snabble/iOS-SDK pull request #246
Opened 2023-04-11 10:20 UTC by utilem

New Deactivate button for CouponViewController, rewritten for SwiftUI.
https://snabble.atlassian.net/browse/APPS-764

TODO: The user must be informed if a coupon could not applied to a cart. This info is only available after the backend returns all lineItems:
See: https://snabble.atlassian.net/browse/APPS-792

2023-04-11 12:43 UTC, mrgrauel requested changes

2023-04-11 12:43 UTC, mrgrauel commented on Sources/UI/Coupons/CouponViewController.swift
> +                .foregroundColor(.systemGreen)
Müssen wir hier nicht wieder durch den AssetProvider?

2023-04-12 04:43 UTC, utilem commented on CHANGELOG.md
> +* Refactured CouponViewController #APPS-764
c305b0820ff25447bd34162627834168f4a2e13e

2023-04-12 05:22 UTC, utilem commented on Sources/UI/Coupons/CouponViewController.swift
> +            }
4bde88d936eeef067b9ac1aa0e6ed0111a71cfca

2023-04-12 08:06 UTC, mrgrauel commented on Sources/UI/Coupons/CouponViewController.swift
> +                .foregroundColor(.systemGreen)
Nein, mit der Farbe.

2023-04-12 08:15 UTC, mrgrauel commented on Sources/UI/Coupons/CouponViewModel.swift
> +    }
Habe ich mit 4d598d26028043325e4600aca045bb07e86f5a86 angepasst. Durch den Stand wird das Image mehrmals gepublished.

2023-04-12 08:52 UTC, mrgrauel approved these changes

2023-04-12 08:54 UTC, merged