Remove UIEmptyState dependency
snabble/iOS-SDK pull request #6
Opened 2020-12-17 14:54 UTC by mrgrauel

* remove pod `UIEmptyState` from depedencies for UI
* increased version in pod to `0.14.10`
* add `InformationButtonView` for emptyView in `PaymentMethodListViewController`

2020-12-17 16:13 UTC, gereons requested changes

2020-12-17 16:13 UTC, gereons commented on Snabble/UI/PaymentMethods/PaymentMethodListViewController.swift
> +        paymentDetails.count == 0 ? showEmptyView() : hideEmptyView()
Lieber isEmpty statt count - meckert bei dir SwiftLint da nicht?

2020-12-17 16:13 UTC, gereons commented on Snabble/UI/Utilities/InformationButtonView.swift
> +
hier meckert SwiftLint wg. trailing whitespace - bei dir nicht?

2020-12-17 19:16 UTC, mrgrauel commented on Snabble/UI/PaymentMethods/PaymentMethodListViewController.swift
> +        paymentDetails.count == 0 ? showEmptyView() : hideEmptyView()
cddfc63751ff089cafde4c489d374914bf2e0225

2020-12-17 19:16 UTC, mrgrauel commented on Snabble/UI/Utilities/InformationButtonView.swift
> +
9af4bdf9ece0ccd63c1b90ba5f5c36923f40840f

2020-12-17 19:17 UTC, mrgrauel reviewed
@gereons leider funktioniert SwiftLint bei mir im SDK nicht. Muss ich mir das Setup genauer angucken.

2020-12-18 12:13 UTC, gereons approved these changes

2020-12-18 12:15 UTC, merged