ScanConfirmationView programmatic layout added; methods naming fixed
snabble/iOS-SDK pull request #99
Opened 2022-04-14 07:36 UTC by mobileapps23

2022-04-14 11:56 UTC, mrgrauel requested changes

2022-04-14 11:56 UTC, mrgrauel commented on Snabble/UI/Scanner/ScanConfirmationView.swift
> +        subtitleLabel.text = "Brand"
Why did you set the text? Shouldn't it be ok that it's empty?

2022-04-14 11:56 UTC, mrgrauel commented on Snabble/UI/Scanner/ScanConfirmationView.swift
> +        productNameLabel.text = "Name"
Why did you set the text? Shouldn't it be ok that it's empty?

2022-04-14 11:56 UTC, mrgrauel commented on Snabble/UI/Scanner/ScanConfirmationView.swift
> +        originalPriceLabel.text = "Orig Price"
Why did you set the text? Shouldn't it be ok that it's empty?

2022-04-14 11:56 UTC, mrgrauel commented on Snabble/UI/Scanner/ScanConfirmationView.swift
> +        priceLabel.text = "Price"
Why did you set the text? Shouldn't it be ok that it's empty?

2022-04-14 13:17 UTC, mobileapps23 commented
Label's placeholders was removed.

2022-04-19 13:42 UTC, mrgrauel approved these changes

2022-04-19 13:42 UTC, merged